2022-02-14 23:34:24,901 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from /N/u/soodn/Carbonate/.config/wandb/settings
2022-02-14 23:34:24,909 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/settings
2022-02-14 23:34:24,911 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-14 23:34:24,912 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'models/5-Deepflash2/Deepflash2-Train-Colon.py', 'program': '/geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/Deepflash2-Train-Colon.py'}
2022-02-14 23:34:24,913 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-14 23:34:24,914 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-14 23:34:24,915 INFO    MainThread:36798 [wandb_init.py:_log_setup():386] Logging user logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220214_233424-1daq31yk/logs/debug.log
2022-02-14 23:34:24,916 INFO    MainThread:36798 [wandb_init.py:_log_setup():387] Logging internal logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220214_233424-1daq31yk/logs/debug-internal.log
2022-02-14 23:34:24,917 INFO    MainThread:36798 [wandb_init.py:init():420] calling init triggers
2022-02-14 23:34:24,917 INFO    MainThread:36798 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-14 23:34:24,917 INFO    MainThread:36798 [wandb_init.py:init():441] re-initializing run, found existing run on stack: 3uzsxm35
2022-02-14 23:34:24,918 INFO    MainThread:36798 [wandb_run.py:finish():1468] finishing run soodn/bricknet/3uzsxm35
2022-02-14 23:34:24,919 INFO    MainThread:36798 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-14 23:34:24,923 INFO    MainThread:36798 [wandb_run.py:_restore():1769] restore
2022-02-14 23:34:27,594 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 904
}

2022-02-14 23:34:27,811 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 904
}

2022-02-14 23:34:28,403 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 19196
}

2022-02-14 23:34:28,515 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2041
  total_bytes: 19196
}

2022-02-14 23:34:28,619 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}

2022-02-14 23:34:28,721 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}

2022-02-14 23:34:28,825 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}

2022-02-14 23:34:28,929 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}

2022-02-14 23:34:29,243 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}

2022-02-14 23:34:29,448 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19196
}
local_info {
}

2022-02-14 23:34:30,759 INFO    MainThread:36798 [wandb_run.py:_append_history():2144] rendering history
2022-02-14 23:34:30,761 INFO    MainThread:36798 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-14 23:34:30,763 INFO    MainThread:36798 [wandb_run.py:_append_files():2194] logging synced files
2022-02-14 23:34:30,775 INFO    MainThread:36798 [wandb_init.py:init():471] starting backend
2022-02-14 23:34:30,775 INFO    MainThread:36798 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-14 23:34:30,783 INFO    MainThread:36798 [backend.py:ensure_launched():219] starting backend process...
2022-02-14 23:34:30,868 INFO    MainThread:36798 [backend.py:ensure_launched():224] started backend process with pid: 2583
2022-02-14 23:34:30,870 INFO    MainThread:36798 [wandb_init.py:init():480] backend started and connected
2022-02-14 23:34:30,882 INFO    MainThread:36798 [wandb_init.py:init():550] updated telemetry
2022-02-14 23:34:31,211 INFO    MainThread:36798 [wandb_init.py:init():581] communicating current version
2022-02-14 23:34:36,212 INFO    MainThread:36798 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-14 23:34:47,934 INFO    MainThread:36798 [wandb_init.py:init():624] starting run threads in backend
2022-02-14 23:34:52,940 INFO    MainThread:36798 [wandb_run.py:_console_start():1827] atexit reg
2022-02-14 23:34:52,943 INFO    MainThread:36798 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.REDIRECT
2022-02-14 23:34:52,944 INFO    MainThread:36798 [wandb_run.py:_redirect():1706] Redirecting console.
2022-02-14 23:34:52,945 INFO    MainThread:36798 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-14 23:34:52,946 INFO    MainThread:36798 [wandb_init.py:init():651] run started, returning control to user process
2022-02-14 23:34:57,565 INFO    MainThread:36798 [wandb_run.py:_config_callback():966] config_cb None None {'Learner': {'loss_func': 'JointLoss(\n  (first): WeightedLoss(\n    (loss): TorchLoss(\n      (loss): DiceLoss()\n    )\n  )\n  (second): WeightedLoss()\n)', 'opt_func': 'fastai.optimizer.ranger', 'lr': 0.001, 'splitter': 'fastai.torch_core.trainable_params', 'metrics': ['<hubmap_loss_metrics.Dice object at 0x2b9a500cd310>', '<hubmap_loss_metrics.Iou object at 0x2b9a500cd4c0>', '<hubmap_loss_metrics.Recall object at 0x2b9a500cd520>', '<hubmap_loss_metrics.Precision object at 0x2b9a500cd580>'], 'path': '.', 'model_dir': 'models', 'wd': 0.0001, 'wd_bn_bias': False, 'train_bn': True, 'moms': [0.95, 0.85, 0.95], '_name': '<fastai.learner.Learner object at 0x2b9a53a30d00>'}, 'TrainEvalCallback': True, 'Recorder': {'add_time': True, 'train_metrics': False, 'valid_metrics': True}, 'ProgressCallback': True, 'SaveModelCallback': {'fname': 'model', 'every_epoch': False, 'at_end': False, 'with_opt': False}, 'ElasticDeformCallback': True, 'WandbCallback': {'log': 'gradients', 'log_preds': False, 'log_model': False, 'log_dataset': False, 'dataset_name': None, 'valid_dl': None, 'n_preds': 36, 'seed': 12345, 'reorder': True}, 'MixedPrecision': True, 'ParamScheduler': True, 'n_inp': 1, 'input 1 dim 1': 32, 'input 1 dim 2': 3, 'input 1 dim 3': 512, 'input 1 dim 4': 512, 'batch size': 32, 'batch per epoch': 18, 'model parameters': 10046436, 'device': 'cuda', 'frozen': False, 'frozen idx': 0}
2022-02-14 23:46:15,616 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from /N/u/soodn/Carbonate/.config/wandb/settings
2022-02-14 23:46:15,624 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/settings
2022-02-14 23:46:15,624 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-14 23:46:15,625 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'models/5-Deepflash2/Deepflash2-Train-Colon.py', 'program': '/geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/Deepflash2-Train-Colon.py'}
2022-02-14 23:46:15,626 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-14 23:46:15,626 INFO    MainThread:36798 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-14 23:46:15,627 INFO    MainThread:36798 [wandb_init.py:_log_setup():386] Logging user logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220214_234615-35jvy3mw/logs/debug.log
2022-02-14 23:46:15,627 INFO    MainThread:36798 [wandb_init.py:_log_setup():387] Logging internal logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220214_234615-35jvy3mw/logs/debug-internal.log
2022-02-14 23:46:15,628 INFO    MainThread:36798 [wandb_init.py:init():420] calling init triggers
2022-02-14 23:46:15,629 INFO    MainThread:36798 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-14 23:46:15,629 INFO    MainThread:36798 [wandb_init.py:init():441] re-initializing run, found existing run on stack: 1daq31yk
2022-02-14 23:46:15,630 INFO    MainThread:36798 [wandb_run.py:finish():1468] finishing run soodn/bricknet/1daq31yk
2022-02-14 23:46:15,631 INFO    MainThread:36798 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-14 23:46:15,636 INFO    MainThread:36798 [wandb_run.py:_restore():1769] restore
2022-02-14 23:46:17,873 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 904
}

2022-02-14 23:46:18,043 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 904
}

2022-02-14 23:46:18,571 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 904
  total_bytes: 19259
}

2022-02-14 23:46:18,674 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2041
  total_bytes: 19259
}

2022-02-14 23:46:18,778 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}

2022-02-14 23:46:18,882 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}

2022-02-14 23:46:18,986 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}

2022-02-14 23:46:19,091 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}

2022-02-14 23:46:19,338 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}

2022-02-14 23:46:19,544 INFO    MainThread:36798 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19259
  total_bytes: 19259
}
local_info {
}

2022-02-14 23:46:20,854 INFO    MainThread:36798 [wandb_run.py:_append_history():2144] rendering history
2022-02-14 23:46:20,856 INFO    MainThread:36798 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-14 23:46:20,857 INFO    MainThread:36798 [wandb_run.py:_append_files():2194] logging synced files
